'use client';

import {
  Brain,
  Eye,
  FileText,
  Gift,
  Heart,
  Lightbulb,
  Lock,
  MessageCircleHeart,
  Sparkles,
  Users,
  Zap,
} from 'lucide-react';
import Link from 'next/link';

import {
  TianjiLoveButton,
  TianjiLoveFooter,
  TianjiLoveHeader,
  TianjiLovePanel,
  TianjiLoveSectionTitle,
  TianjiLoveShell,
  getTianjiLoveFooterNav,
  getTianjiLovePrimaryNav,
} from '@/components/tianji-love';
import { useSyncedLanguage } from '@/hooks/useSyncedLanguage';
import { withLanguageParam } from '@/lib/language-routing';

const INTERNAL_LINKS = [
  { href: '/guide', labelEn: 'Guides', labelZh: '指南' },
  { href: '/love-test', labelEn: 'Love Test', labelZh: '感情测试' },
  { href: '/about', labelEn: 'About', labelZh: '关于' },
  { href: '/services', labelEn: 'Services', labelZh: '服务' },
];

const DISCLAIMER_EN =
  'tianji.love provides entertainment and self-reflection tools. Results are for reference only and do not constitute professional advice.';
const DISCLAIMER_ZH =
  'tianji.love 提供娱乐与自我探索工具，结果仅供参考，不构成专业建议。';

const FAQS = [
  {
    qEn: 'What exactly is an AI love reading?',
    qZh: 'AI爱情解读到底是什么？',
    aEn: 'An AI love reading is an astrology-informed relationship analysis generated by our engine. It takes your birth data (or just names for a lighter preview) and produces a structured reflection on your compatibility, timing, and communication patterns. The AI helps translate complex astrological data into practical, personal insights.',
    aZh: 'AI爱情解读是由我们的引擎生成的星象关系分析。它接收你的出生数据（或仅为轻量预览的名字），并对你的适合度、时机和沟通模式产生结构化的反思。AI帮助将复杂的星象数据转化为实用、个性化的见解。',
  },
  {
    qEn: 'How long does a free reading take?',
    qZh: '免费解读需要多长时间？',
    aEn: 'A free preview reading takes under 2 minutes to generate. You will receive a quick relationship snapshot covering compatibility highlights, a current timing signal, and reflection prompts. The full premium report takes a few minutes more and goes significantly deeper.',
    aZh: '免费预览解读生成时间不到2分钟。你将收到一份快速关系快照，包括适合度亮点、当前时机信号和反思提示。完整的高级报告需要几分钟，但内容深入得多。',
  },
  {
    qEn: 'Is my birth data kept private?',
    qZh: '我的出生数据是否保密？',
    aEn: 'Yes. Your birth date, birth time, and birth location are used only to calculate your chart and generate your reading. They are never shared, sold, or stored beyond the session unless you explicitly create an account. No account is required for a free preview.',
    aZh: '是的。你的出生日期、出生时间和出生地点仅用于计算星盘和生成解读。除非你明确创建账户，否则它们永远不会在会话之外被共享、出售或存储。免费预览无需账户。',
  },
  {
    qEn: 'What is the difference between free and paid?',
    qZh: '免费和付费有什么区别？',
    aEn: 'The free preview gives you a structured quick read: a compatibility snapshot, one current timing signal, and guided reflection questions. The paid full report unlocks the complete analysis — all five compatibility dimensions, every timing window, detailed communication guidance, and personalized next steps.',
    aZh: '免费预览为你提供结构化的快速解读：适合度快照、一个当前时机信号和有引导的反思问题。付费完整报告解锁完整分析——所有五个适合度维度、每个时机窗口、详细的沟通指导和个性化的下一步。',
  },
  {
    qEn: 'Can I trust the AI accuracy?',
    qZh: '我能相信AI的准确性吗？',
    aEn: 'Our engine combines traditional astrology formulas with AI interpretation layers. Results are deterministic in their calculations — the same inputs always produce the same astrological data. The AI layer provides natural-language explanations that are contextually informed by your specific chart. We recommend treating all readings as self-reflection tools rather than absolute predictions.',
    aZh: '我们的引擎将传统星盘公式与AI解释层相结合。计算结果是确定性的——相同的输入总是产生相同的星象数据。AI层提供由你的特定星盘情境信息驱动的自然语言解释。我们建议将所有解读视为自我反思工具，而不是绝对预测。',
  },
];

const TOPICS_COVERED = [
  {
    icon: Heart,
    titleEn: 'Compatibility Overview',
    titleZh: '适合度概览',
    descEn: 'Core compatibility score across emotional, communication, and values dimensions.',
    descZh: '情感、沟通和价值观维度的核心适合度评分。',
  },
  {
    icon: Zap,
    titleEn: 'Timing Signals',
    titleZh: '时机信号',
    descEn: 'Current planetary transits affecting your relationship window — when to act, wait, or reflect.',
    descZh: '影响你关系窗口的当前行星行运——何时行动、等待或反思。',
  },
  {
    icon: MessageCircleHeart,
    titleEn: 'Communication Style',
    titleZh: '沟通风格',
    descEn: 'How you and your partner process and express emotions, and where friction may arise.',
    descZh: '你和伴侣处理和表达情感的方式，以及可能产生摩擦的地方。',
  },
  {
    icon: Eye,
    titleEn: 'Next Steps',
    titleZh: '下一步',
    descEn: 'Practical, personalized guidance for the next 30 days based on your current chart state.',
    descZh: '基于你当前星盘状态的未来30天的实用个性化指导。',
  },
];

export default function FreeAILoveReadingPage() {
  const [language, setLanguage] = useSyncedLanguage('en');

  const t = (en: string, zh: string) => (language === 'zh' ? zh : en);
  const navItems = getTianjiLovePrimaryNav(language);
  const footerLinks = getTianjiLoveFooterNav(language);
  const href = (path: string) => withLanguageParam(path, language);

  const toggleLanguage = () => {
    const next = language === 'zh' ? 'en' : 'zh';
    setLanguage(next);
  };

  const faqPageSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: FAQS.map((faq) => ({
      '@type': 'Question',
      name: t(faq.qEn, faq.qZh),
      acceptedAnswer: {
        '@type': 'Answer',
        text: t(faq.aEn, faq.aZh),
      },
    })),
  };

  return (
    <TianjiLoveShell>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqPageSchema) }}
      />

      <TianjiLoveHeader
        homeHref={href('/')}
        navItems={navItems}
        cta={{ label: t('Start Love Reading', '开始关系解读'), href: href('/relationship/new') }}
        languageLabel={language === 'zh' ? 'EN' : '中文'}
        onLanguageToggle={toggleLanguage}
      />

      {/* Hero */}
      <section className="relative z-10 px-5 pt-20 sm:px-8">
        <div className="mx-auto max-w-4xl text-center">
          <div className="mb-4 flex justify-center">
            <div className="flex h-16 w-16 items-center justify-center rounded-full border border-[#b57248]/38 bg-[#0a1020]/66">
              <Brain className="h-8 w-8 text-[#d8b77b]" aria-hidden />
            </div>
          </div>
          <p className="text-xs uppercase tracking-[0.28em] text-[#d8b77b]/64">
            {t('Instant · Astrology-Informed · Private', '即时 · 星象指导 · 私密')}
          </p>
          <h1 className="mt-4 font-serif text-4xl font-semibold leading-tight text-[#ffe3b4] sm:text-5xl">
            {t('Free AI Love Reading', '免费AI爱情解读')}
          </h1>
          <p className="mx-auto mt-5 max-w-2xl text-base text-[#f4d7a3]/72">
            {t(
              'Get an instant relationship reflection powered by astrology and AI. A quick, free preview that reveals compatibility highlights, timing signals, and reflection prompts.',
              '获取由星象和AI驱动的即时关系反思。快速、免费的预览，揭示适合度亮点、时机信号和反思提示。'
            )}
          </p>
          <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
            <TianjiLoveButton href={href('/relationship/new')} size="lg">
              {t('Get Free Preview', '获取免费预览')}
              <Sparkles className="ml-2 h-5 w-5" aria-hidden />
            </TianjiLoveButton>
            <TianjiLoveButton href={href('/guide')} variant="secondary" size="lg">
              {t('Explore Guides', '探索指南')}
            </TianjiLoveButton>
          </div>
        </div>
      </section>

      {/* What is an AI Love Reading */}
      <section className="relative z-10 mx-auto max-w-4xl px-5 py-16 sm:px-8">
        <TianjiLoveSectionTitle
          title={t('What is an AI Love Reading?', '什么是AI爱情解读？')}
          eyebrow={t('The Technology', '技术解读')}
        />
        <TianjiLovePanel className="mt-6 p-6">
          <p className="text-sm leading-relaxed text-[#f4d7a3]/72">
            {t(
              'An AI love reading combines the precision of traditional astrology with the fluency of modern AI language models. Your birth data — date, time, and location — is processed through our astrology engine to generate the underlying chart data. That data is then interpreted by an AI layer that crafts a personalized, readable narrative around your relationship patterns and timing.',
              'AI爱情解读将传统星象学的精确性与现代AI语言模型的流畅性相结合。你的出生数据——日期、时间和地点——通过我们的星象引擎处理，生成底层星盘数据。然后由AI层解释这些数据，为你的关系模式和时机创作个性化的可读叙述。'
            )}
          </p>
          <p className="mt-4 text-sm leading-relaxed text-[#f4d7a3]/72">
            {t(
              'Think of it as having an astrology assistant who never sleeps, can process multiple chart layers simultaneously, and explains everything in plain language. The result is a reading that feels personal, not generic.',
              '可以把它想象成一个不知疲倦的星象助手，可以同时处理多个星盘层面，并用通俗易懂的语言解释一切。结果是一份感觉个性化而非泛泛的解读。'
            )}
          </p>
        </TianjiLovePanel>
      </section>

      {/* What to Expect */}
      <section className="relative z-10 mx-auto max-w-4xl px-5 py-8 sm:px-8">
        <TianjiLoveSectionTitle
          title={t('What to Expect', '你会得到什么')}
          eyebrow={t('The Experience', '体验')}
        />
        <TianjiLovePanel className="mt-6 p-6">
          <div className="space-y-4">
            <div className="flex gap-4">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-[#b57248]/38 bg-[#0a1020]/66">
                <Zap className="h-4 w-4 text-[#d8b77b]" aria-hidden />
              </div>
              <div>
                <h3 className="font-serif text-base font-semibold text-[#ffe3b4]">
                  {t('Quick Turnaround', '快速生成')}
                </h3>
                <p className="mt-1 text-sm text-[#f4d7a3]/62">
                  {t('Free preview results in under 2 minutes. Full reports generate in a few minutes more.', '免费预览结果在2分钟内生成。完整报告需要几分钟。')}
                </p>
              </div>
            </div>
            <div className="flex gap-4">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-[#b57248]/38 bg-[#0a1020]/66">
                <FileText className="h-4 w-4 text-[#d8b77b]" aria-hidden />
              </div>
              <div>
                <h3 className="font-serif text-base font-semibold text-[#ffe3b4]">
                  {t('Structured Output', '结构化输出')}
                </h3>
                <p className="mt-1 text-sm text-[#f4d7a3]/62">
                  {t('Every reading follows a clear structure: compatibility snapshot, timing signal, reflection prompts.', '每份解读都遵循清晰的结构：适合度快照、时机信号、反思提示。')}
                </p>
              </div>
            </div>
            <div className="flex gap-4">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-[#b57248]/38 bg-[#0a1020]/66">
                <Lightbulb className="h-4 w-4 text-[#d8b77b]" aria-hidden />
              </div>
              <div>
                <h3 className="font-serif text-base font-semibold text-[#ffe3b4]">
                  {t('Reflection Prompts', '反思提示')}
                </h3>
                <p className="mt-1 text-sm text-[#f4d7a3]/62">
                  {t('Actionable questions to take the insights into your real life and relationships.', '可操作的问题，将洞察带入你的现实生活和感情中。')}
                </p>
              </div>
            </div>
          </div>
        </TianjiLovePanel>
      </section>

      {/* Topics Covered */}
      <section className="relative z-10 mx-auto max-w-7xl px-5 py-8 sm:px-8">
        <TianjiLoveSectionTitle
          title={t('Topics Covered', '涵盖主题')}
          eyebrow={t('Scope', '范围')}
        />
        <div className="mt-6 grid gap-6 sm:grid-cols-2">
          {TOPICS_COVERED.map((topic) => {
            const Icon = topic.icon;
            return (
              <TianjiLovePanel key={topic.titleEn} className="flex flex-col p-6">
                <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full border border-[#b57248]/38 bg-[#0a1020]/66">
                  <Icon className="h-6 w-6 text-[#d8b77b]" aria-hidden />
                </div>
                <h3 className="font-serif text-lg font-semibold text-[#ffe3b4]">
                  {t(topic.titleEn, topic.titleZh)}
                </h3>
                <p className="mt-2 flex-1 text-sm leading-relaxed text-[#f4d7a3]/62">
                  {t(topic.descEn, topic.descZh)}
                </p>
              </TianjiLovePanel>
            );
          })}
        </div>
      </section>

      {/* AdSense placeholder */}
      <div id="free-ai-reading-ads" className="relative z-10 mx-auto max-w-7xl px-5 py-8 sm:px-8" />

      {/* Free vs Paid */}
      <section className="relative z-10 mx-auto max-w-4xl px-5 py-8 sm:px-8">
        <TianjiLoveSectionTitle
          title={t('Free vs Paid', '免费与付费')}
          eyebrow={t('Choose Your Depth', '选择深度')}
        />
        <div className="mt-6 grid gap-6 sm:grid-cols-2">
          {/* Free */}
          <TianjiLovePanel className="flex flex-col p-6">
            <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full border border-[#b57248]/38 bg-[#0a1020]/66">
              <Gift className="h-6 w-6 text-[#d8b77b]" aria-hidden />
            </div>
            <h3 className="font-serif text-xl font-semibold text-[#ffe3b4]">
              {t('Free Preview', '免费预览')}
            </h3>
            <ul className="mt-4 space-y-2">
              {[
                t('Quick compatibility snapshot', '快速适合度快照'),
                t('One current timing signal', '一个当前时机信号'),
                t('Reflection prompts', '反思提示'),
                t('No account required', '无需账户'),
                t('Instant results', '即时结果'),
              ].map((item) => (
                <li key={item} className="flex gap-2 text-sm text-[#f4d7a3]/62">
                  <span className="text-[#d8b77b]">✓</span>
                  {item}
                </li>
              ))}
            </ul>
            <TianjiLoveButton href={href('/relationship/new')} variant="secondary" className="mt-6">
              {t('Get Free Preview', '获取免费预览')}
            </TianjiLoveButton>
          </TianjiLovePanel>

          {/* Paid */}
          <TianjiLovePanel className="relative flex flex-col p-6">
            <div className="absolute -top-3 right-4 rounded-full bg-[#d8b77b] px-3 py-1 text-xs font-semibold text-[#0a1020]">
              {t('Recommended', '推荐')}
            </div>
            <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full border border-[#b57248]/38 bg-[#0a1020]/66">
              <Sparkles className="h-6 w-6 text-[#d8b77b]" aria-hidden />
            </div>
            <h3 className="font-serif text-xl font-semibold text-[#ffe3b4]">
              {t('Full Report', '完整报告')}
            </h3>
            <ul className="mt-4 space-y-2">
              {[
                t('Complete 5-dimension analysis', '完整5维度分析'),
                t('All timing windows explained', '所有时机窗口详解'),
                t('Detailed communication guide', '详细沟通指南'),
                t('Personalized 30-day action plan', '个性化30天行动计划'),
                t('Pattern history and healing cues', '模式历史与疗愈提示'),
                t('Shareable result page', '可分享结果页面'),
              ].map((item) => (
                <li key={item} className="flex gap-2 text-sm text-[#f4d7a3]/62">
                  <span className="text-[#d8b77b]">✓</span>
                  {item}
                </li>
              ))}
            </ul>
            <TianjiLoveButton href={href('/relationship/new')} className="mt-6">
              {t('Unlock Full Report', '解锁完整报告')}
              <Sparkles className="ml-2 h-4 w-4" aria-hidden />
            </TianjiLoveButton>
          </TianjiLovePanel>
        </div>
      </section>

      {/* Privacy */}
      <section className="relative z-10 mx-auto max-w-4xl px-5 py-8 sm:px-8">
        <TianjiLoveSectionTitle
          title={t('Your Privacy is Protected', '你的隐私受到保护')}
          eyebrow={t('Privacy First', '隐私优先')}
        />
        <TianjiLovePanel className="mt-6 flex flex-col items-center p-6 text-center sm:flex-row sm:text-left">
          <div className="mb-4 flex h-14 w-14 shrink-0 items-center justify-center rounded-full border border-[#b57248]/38 bg-[#0a1020]/66 sm:mb-0">
            <Lock className="h-7 w-7 text-[#d8b77b]" aria-hidden />
          </div>
          <div className="sm:ml-5">
            <p className="text-sm leading-relaxed text-[#f4d7a3]/72">
              {t(
                'Your birth data — date, time, and location — is used only to generate your reading. It is never stored beyond your session unless you explicitly create an account. No account is required to receive a free preview. We do not sell or share your personal data with third parties.',
                '你的出生数据——日期、时间和地点——仅用于生成你的解读。除非你明确创建账户，否则它永远不会在你的会话之外被存储。免费预览无需账户。我们不出售或与第三方共享你的个人数据。'
              )}
            </p>
            <Link href={href('/privacy-center')} className="mt-2 inline-block text-sm text-[#d8b77b] underline">
              {t('Learn more about our privacy practices →', '了解更多关于我们隐私实践的信息 →')}
            </Link>
          </div>
        </TianjiLovePanel>
      </section>

      {/* CTA Banner */}
      <section className="relative z-10 px-5 pb-8 sm:px-8">
        <TianjiLovePanel className="mx-auto max-w-3xl p-8 text-center">
          <Users className="mx-auto mb-4 h-10 w-10 text-[#d8b77b]" aria-hidden />
          <h2 className="font-serif text-2xl font-semibold text-[#ffe3b4]">
            {t('Ready to discover what the stars say?', '准备好发现星星说什么了吗？')}
          </h2>
          <p className="mt-3 text-sm text-[#f4d7a3]/62">
            {t(
              'Start with a free preview — no signup required. Unlock the full report when you are ready for deeper insights.',
              '从免费预览开始——无需注册。当你准备好获取更深入的洞察时，解锁完整报告。'
            )}
          </p>
          <TianjiLoveButton href={href('/relationship/new')} className="mt-6">
            {t('Start Free Love Reading', '开始免费爱情解读')}
            <Brain className="ml-2 h-4 w-4" aria-hidden />
          </TianjiLoveButton>
        </TianjiLovePanel>
      </section>

      {/* AdSense placeholder */}
      <div id="free-ai-reading-ads" className="relative z-10 mx-auto max-w-7xl px-5 py-8 sm:px-8" />

      {/* FAQ */}
      <section className="relative z-10 mx-auto max-w-4xl px-5 pb-8 sm:px-8">
        <TianjiLoveSectionTitle
          title={t('Frequently Asked Questions', '常见问题')}
          eyebrow={t('FAQ', '问答')}
        />
        <div className="mt-8 space-y-4">
          {FAQS.map((faq, i) => (
            <TianjiLovePanel key={i} className="p-6">
              <h3 className="font-serif text-base font-semibold text-[#ffe3b4]">
                {t(faq.qEn, faq.qZh)}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-[#f4d7a3]/62">
                {t(faq.aEn, faq.aZh)}
              </p>
            </TianjiLovePanel>
          ))}
        </div>
      </section>

      {/* Internal Links */}
      <nav className="relative z-10 flex justify-center gap-8 pb-8 text-sm text-[#f4d7a3]/56">
        {INTERNAL_LINKS.map((link) => (
          <Link key={link.href} href={href(link.href)} className="transition hover:text-[#ffe3b4]">
            {t(link.labelEn, link.labelZh)}
          </Link>
        ))}
      </nav>

      <TianjiLoveFooter
        disclaimer={t(DISCLAIMER_EN, DISCLAIMER_ZH)}
        links={footerLinks}
        homeHref={href('/')}
      />
    </TianjiLoveShell>
  );
}
