'use client';

import Link from 'next/link';
import { useState } from 'react';

export default function PrivacyPage() {
  const [language, setLanguage] = useState<'zh' | 'en'>('zh');
  const [activeSection, setActiveSection] = useState<number | null>(null);

  const content = {
    zh: {
      title: '隐私政策',
      lastUpdated: '最后更新：2024年12月',
      intro: '天机全球（"我们"、"我们的"或"天机"）致力于保护您的隐私。本隐私政策解释了我们如何收集、使用、披露和保护您的个人信息。',
      sections: [
        {
          title: '信息收集',
          icon: '📋',
          content: `我们收集以下类型的信息：

• 您主动提供的信息：您在注册账户、订阅服务或填写表单时提供的姓名、电子邮件地址、出生日期、性别等。
• 来自Chinese metaphysics服务的数据：当您使用我们的八字、命理、紫微斗数、易经等服务时，您提供的信息以及由我们的AI系统分析得出的洞察。
• 支付信息：我们通过第三方支付处理器处理付款，我们不会存储您的完整信用卡信息。
• 技术数据：IP地址、浏览器类型、设备标识符、cookies以及您如何使用我们的服务的技术日志。`
        },
        {
          title: '数据使用',
          icon: '🔍',
          content: `我们使用收集的数据用于：

• 提供和改善我们的服务：包括AI驱动的命理分析、个性化内容推荐。
• 账户管理：处理注册、登录、密码重置等服务。
• 通信：发送与服务相关的通知、更新、营销通讯（您可以随时选择退出）。
• 安全和防欺诈：检测和预防欺诈、滥用或未经授权的访问。
• 法律合规：遵守适用的法律和监管要求。`
        },
        {
          title: '数据存储与安全',
          icon: '🔐',
          content: `数据存储：
• 您的数据存储在安全的云服务器上。
• 我们使用行业标准的加密技术保护数据传输和存储。

数据保留：
• 账户数据保留至您删除账户为止。
• 分析数据在匿名化后可能保留更长时间。

安全性：
• 我们实施多层次安全措施，包括防火墙、入侵检测和定期安全审计。
• 所有数据传输使用SSL/TLS加密。`
        },
        {
          title: 'Cookies',
          icon: '🍪',
          content: `我们使用cookies和类似技术：

• 必要的Cookies：确保网站正常运作所必需的cookies。
• 分析Cookies：帮助我们了解用户如何使用我们的网站。
• 功能Cookies：记住您的偏好设置。

您可以通过浏览器设置管理或禁用cookies，但这可能影响网站功能。`
        },
        {
          title: '您的权利（GDPR/CCPA）',
          icon: '⚖️',
          content: `根据您所在的司法管辖区，您可能有权：

• 访问您的个人数据
• 更正不准确的数据
• 删除您的数据（"被遗忘权"）
• 限制或反对数据处理
• 数据可携带权
• 撤回同意权
• 向监管机构投诉的权利

如需行使这些权利，请联系：hello@tianji.global`
        },
        {
          title: '联系我们',
          icon: '📧',
          content: `如果您对本隐私政策有任何疑问或疑虑，请联系我们：

• 电子邮件：hello@tianji.global
• 网站：https://tianji.global

我们将尽快回复您的请求，并在30天内予以处理。`
        }
      ]
    },
    en: {
      title: 'Privacy Policy',
      lastUpdated: 'Last updated: December 2024',
      intro: 'TianJi Global ("we", "our", or "TianJi") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information.',
      sections: [
        {
          title: 'Information We Collect',
          icon: '📋',
          content: `We collect the following types of information:

• Information you provide: Name, email address, date of birth, gender, and other details you provide when registering for an account, subscribing to services, or filling out forms.
• Data from Chinese metaphysics services: Information you provide and insights generated by our AI systems when you use our Bazi, Ming Li, Zi Wei Dou Shu, Yi Jing, and other services.
• Payment information: We process payments through third-party payment processors. We do not store your complete credit card information.
• Technical data: IP address, browser type, device identifiers, cookies, and technical logs of how you use our services.`
        },
        {
          title: 'How We Use Your Data',
          icon: '🔍',
          content: `We use the collected data for:

• Providing and improving our services: Including AI-driven fortune analysis and personalized content recommendations.
• Account management: Processing registration, login, password reset, and other services.
• Communication: Sending service-related notifications, updates, and marketing communications (you can opt out at any time).
• Security and fraud prevention: Detecting and preventing fraud, abuse, or unauthorized access.
• Legal compliance: Complying with applicable laws and regulatory requirements.`
        },
        {
          title: 'Data Storage & Security',
          icon: '🔐',
          content: `Data Storage:
• Your data is stored on secure cloud servers.
• We use industry-standard encryption technologies to protect data in transit and at rest.

Data Retention:
• Account data is retained until you delete your account.
• Analytical data may be retained longer after anonymization.

Security:
• We implement multi-layered security measures including firewalls, intrusion detection, and regular security audits.
• All data transmissions are encrypted using SSL/TLS.`
        },
        {
          title: 'Cookies',
          icon: '🍪',
          content: `We use cookies and similar technologies:

• Essential Cookies: Necessary for the website to function properly.
• Analytics Cookies: Help us understand how users use our website.
• Functional Cookies: Remember your preferences.

You can manage or disable cookies through your browser settings, but this may affect website functionality.`
        },
        {
          title: 'Your Rights (GDPR/CCPA)',
          icon: '⚖️',
          content: `Depending on your jurisdiction, you may have the right to:

• Access your personal data
• Correct inaccurate data
• Delete your data ("Right to be Forgotten")
• Restrict or object to data processing
• Data portability
• Withdraw consent
• File a complaint with a supervisory authority

To exercise these rights, please contact: hello@tianji.global`
        },
        {
          title: 'Contact Us',
          icon: '📧',
          content: `If you have any questions or concerns about this Privacy Policy, please contact us:

• Email: hello@tianji.global
• Website: https://tianji.global

We will respond to your requests as soon as possible and process them within 30 days.`
        }
      ]
    }
  };

  const t = content[language];

  return (
    <main className="min-h-screen relative overflow-hidden">
      {/* Animated Background */}
      <div className="absolute inset-0 bg-gradient-to-br from-slate-900 via-purple-950 to-slate-900">
        <div className="stars-container">
          {[...Array(100)].map((_, i) => (
            <div
              key={i}
              className="star"
              style={{
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
                animationDelay: `${Math.random() * 3}s`,
                animationDuration: `${2 + Math.random() * 2}s`,
              }}
            />
          ))}
        </div>
        <div className="absolute top-20 left-20 w-96 h-96 bg-purple-600/20 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-20 right-20 w-80 h-80 bg-amber-500/10 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '1s' }} />
      </div>

      <div className="relative z-10">
        {/* Header */}
        <header className="p-6">
          <div className="flex justify-between items-center max-w-7xl mx-auto">
            <div>
              <h1 className="text-3xl md:text-4xl font-bold bg-gradient-to-r from-purple-400 via-pink-400 to-amber-400 bg-clip-text text-transparent">
                天机全球
              </h1>
              <p className="text-purple-300/80 text-lg">TianJi Global</p>
            </div>
            <div className="flex items-center gap-4">
              <Link
                href="/"
                className="px-4 py-2 bg-slate-800/50 text-white rounded-lg text-sm font-medium hover:bg-slate-700 transition"
              >
                {language === 'zh' ? '返回首页' : 'Back to Home'}
              </Link>
              <button
                onClick={() => setLanguage('zh')}
                className={`px-3 py-1 rounded-full text-sm transition-all ${
                  language === 'zh'
                    ? 'bg-purple-600 text-white'
                    : 'bg-slate-800/50 text-slate-300 hover:bg-slate-700'
                }`}
              >
                中文
              </button>
              <button
                onClick={() => setLanguage('en')}
                className={`px-3 py-1 rounded-full text-sm transition-all ${
                  language === 'en'
                    ? 'bg-purple-600 text-white'
                    : 'bg-slate-800/50 text-slate-300 hover:bg-slate-700'
                }`}
              >
                EN
              </button>
            </div>
          </div>
        </header>

        {/* Content */}
        <section className="px-6 py-12 md:py-20 max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
              {t.title}
            </h2>
            <p className="text-purple-300 text-sm">{t.lastUpdated}</p>
            <p className="text-slate-400 mt-4 max-w-2xl mx-auto">{t.intro}</p>
          </div>

          {/* Sections */}
          <div className="space-y-4">
            {t.sections.map((section, index) => (
              <div
                key={index}
                className="rounded-2xl bg-slate-800/50 backdrop-blur-sm border border-slate-700/50 overflow-hidden transition-all duration-300"
              >
                <button
                  onClick={() => setActiveSection(activeSection === index ? null : index)}
                  className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-slate-700/30 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">{section.icon}</span>
                    <h3 className="text-xl font-semibold text-white">{section.title}</h3>
                  </div>
                  <svg
                    className={`w-5 h-5 text-slate-400 transition-transform duration-300 ${activeSection === index ? 'rotate-180' : ''}`}
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                {activeSection === index && (
                  <div className="px-6 pb-4">
                    <div className="text-slate-300 whitespace-pre-line leading-relaxed pl-9">
                      {section.content}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Footer */}
        <footer className="text-center py-8 text-slate-500 text-sm">
          <p>© 2024 TianJi Global · 天机全球</p>
          <p className="mt-1">
            {language === 'zh'
              ? '融合传统智慧与现代科技'
              : 'Bridging Traditional Wisdom & Modern Technology'}
          </p>
        </footer>
      </div>

      <style jsx>{`
        .stars-container {
          position: absolute;
          inset: 0;
          overflow: hidden;
        }
        .star {
          position: absolute;
          width: 2px;
          height: 2px;
          background: white;
          border-radius: 50%;
          animation: twinkle ease-in-out infinite;
        }
        @keyframes twinkle {
          0%, 100% { opacity: 0.2; transform: scale(1); }
          50% { opacity: 1; transform: scale(1.5); }
        }
      `}</style>
    </main>
  );
}
