import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

import { localizedPublicRoutes } from '@/lib/i18n';

/**
 * T0-001 (SIAS Autonomous Evolution L2, 2026-07-23) regression contract.
 *
 * Locks down the SEO surface added to /daily-oracle so the funnel entry
 * cannot regress to "tracked by analytics but invisible to crawlers":
 *
 *   - localizedPublicRoutes must contain /daily-oracle with priority 0.9.
 *   - src/app/(main)/daily-oracle/layout.tsx must exist and export a
 *     metadata object with title, description, openGraph, twitter, and
 *     alternates.canonical.
 *   - The layout must render at least one <JsonLd> payload (breadcrumb
 *     + web app + FAQ), each carrying a unique @id.
 */
describe('daily-oracle SEO surface (T0-001)', () => {
  it('registers /daily-oracle in localizedPublicRoutes with priority 0.9 and daily changeFrequency', () => {
    const entry = localizedPublicRoutes.find((r) => r.path === '/daily-oracle');
    expect(entry).toBeDefined();
    expect(entry?.priority).toBe(0.9);
    expect(entry?.changeFrequency).toBe('daily');
  });

  it('exposes a server layout.tsx exporting metadata with the expected SEO fields', () => {
    const layoutPath = path.join(
      process.cwd(),
      'src/app/(main)/daily-oracle/layout.tsx'
    );
    expect(fs.existsSync(layoutPath)).toBe(true);

    const source = fs.readFileSync(layoutPath, 'utf8');

    expect(source).toMatch(/export const metadata:\s*Metadata/);
    expect(source).toContain("title:");
    expect(source).toContain("description:");
    expect(source).toContain("openGraph:");
    expect(source).toContain("twitter:");
    expect(source).toContain("alternates:");
    expect(source).toContain("canonical:");
    expect(source).toContain('/daily-oracle');
  });

  it('renders breadcrumb + WebApplication + FAQ JsonLd payloads with unique @ids', () => {
    const layoutPath = path.join(
      process.cwd(),
      'src/app/(main)/daily-oracle/layout.tsx'
    );
    const source = fs.readFileSync(layoutPath, 'utf8');

    // Breadcrumb — produced by buildBreadcrumb(), so the source uses the
    // helper call rather than a literal BreadcrumbList string. The literal
    // shape lives in src/components/seo/JsonLd.tsx.
    expect(source).toContain("buildBreadcrumb(");

    // WebApplication + FAQ are inline literals.
    expect(source).toMatch(/['"]@type['"]:\s*['"]WebApplication['"]/);
    expect(source).toMatch(/['"]@type['"]:\s*['"]FAQPage['"]/);

    // Each payload must carry a unique @id anchor. The breadcrumb @id
    // is generated by buildBreadcrumb (not visible in source), so we
    // count only the inline @id anchors for WebApplication + FAQ +
    // any others in the source.
    const ids = source.match(/['"]@id['"]:\s*[`'"][^`'"]+[`'"]/g) ?? [];
    // At minimum: PAGE_URL#webapp + PAGE_URL#faq = 2 unique inline anchors.
    expect(ids.length).toBeGreaterThanOrEqual(2);
    const uniq = new Set(ids);
    expect(uniq.size).toBe(ids.length);

    // The layout must render at least 3 JsonLd components (breadcrumb +
    // web app + FAQ), one per payload.
    const jsonLdCount = (source.match(/<JsonLd\s+data=/g) ?? []).length;
    expect(jsonLdCount).toBeGreaterThanOrEqual(3);
  });

  it('does not promise guaranteed outcomes in any FAQ or copy field', () => {
    const layoutPath = path.join(
      process.cwd(),
      'src/app/(main)/daily-oracle/layout.tsx'
    );
    const source = fs.readFileSync(layoutPath, 'utf8');
    // Anti-claim: the layout copy must contain a "no guaranteed outcomes"
    // disclaimer (matches pricing/layout.tsx pattern).
    expect(source.toLowerCase()).toContain('does not promise');
    expect(source.toLowerCase()).toMatch(/(no guarantee|not promise|does not promise)/);
  });
});