begin;

insert into public.fortune_remedy_rules (
  rule_key,
  language,
  category,
  trigger_tags,
  severity,
  title,
  rationale,
  action_template,
  safety_note,
  priority,
  metadata
) values
  (
    'steady_morning_breath',
    'en',
    'mindset',
    array['anxious', 'scattered', 'low-clarity'],
    'low',
    'Start with three steady breaths',
    'A short pause can make the day feel less reactive before any decision-heavy work.',
    'Before checking messages, take three slow breaths and name the one thing that matters most today.',
    'This is a general wellbeing prompt, not medical advice.',
    10,
    '{"duration_minutes": 2, "time_of_day": "morning"}'::jsonb
  ),
  (
    'ten_minute_space_reset',
    'en',
    'environment',
    array['blocked', 'heavy-energy', 'low-focus'],
    'low',
    'Reset one small space',
    'A visible reset can create momentum without needing a major life change.',
    'Spend ten minutes clearing the desk, bag, or bedside area you use most often.',
    'Keep the action small and practical.',
    20,
    '{"duration_minutes": 10}'::jsonb
  ),
  (
    'single_next_step',
    'en',
    'focus',
    array['overthinking', 'decision-fatigue', 'stalled'],
    'low',
    'Choose one next step',
    'When energy is split, a single concrete step is safer than forcing a complete plan.',
    'Write one task that can be finished in under twenty minutes, then do only that.',
    'Avoid using this as pressure to overwork.',
    30,
    '{"duration_minutes": 20}'::jsonb
  ),
  (
    'warm_check_in_message',
    'en',
    'relationship',
    array['relationship-tension', 'lonely', 'low-connection'],
    'low',
    'Send a warm check-in',
    'A low-stakes message can reopen connection without demanding a heavy conversation.',
    'Send one kind, simple check-in to someone you trust, with no request attached.',
    'Respect boundaries and do not use this for unsafe relationships.',
    40,
    '{"channel": "message"}'::jsonb
  ),
  (
    'evening_reflection_three_lines',
    'en',
    'routine',
    array['restless', 'unclear-patterns', 'emotional-noise'],
    'low',
    'Close the day in three lines',
    'A brief reflection helps separate signal from noise before sleep.',
    'Tonight, write three lines: what helped, what drained you, and what you will release.',
    'If journaling increases distress, pause and choose a grounding activity instead.',
    50,
    '{"duration_minutes": 5, "time_of_day": "evening"}'::jsonb
  ),
  (
    'gentle_walk_light',
    'en',
    'wellbeing',
    array['stagnant', 'low-mood', 'low-energy'],
    'low',
    'Take a gentle light break',
    'Light movement can help shift attention and restore a sense of pace.',
    'Step outside or near a window for five to ten minutes, keeping the pace easy.',
    'Choose an option that fits your body and environment; this is not medical advice.',
    60,
    '{"duration_minutes": 10}'::jsonb
  ),
  (
    'steady_morning_breath',
    'zh',
    'mindset',
    array['anxious', 'scattered', 'low-clarity'],
    'low',
    '用三次稳定呼吸开场',
    '短暂停顿能让一天不那么被外界牵着走，尤其适合需要做决定的早晨。',
    '查看消息前，慢慢呼吸三次，然后写下今天最重要的一件事。',
    '这是通用身心提示，不构成医疗建议。',
    10,
    '{"duration_minutes": 2, "time_of_day": "morning"}'::jsonb
  ),
  (
    'ten_minute_space_reset',
    'zh',
    'environment',
    array['blocked', 'heavy-energy', 'low-focus'],
    'low',
    '整理一个小空间',
    '一个看得见的小整理，往往比大幅度改变更容易带来行动感。',
    '花十分钟整理最常用的桌面、包或床边区域。',
    '保持动作小而具体，不需要一次整理全部空间。',
    20,
    '{"duration_minutes": 10}'::jsonb
  ),
  (
    'single_next_step',
    'zh',
    'focus',
    array['overthinking', 'decision-fatigue', 'stalled'],
    'low',
    '只选下一步',
    '能量分散时，先完成一个具体动作，通常比强行制定完整计划更稳。',
    '写下一个二十分钟内能完成的小任务，然后只做这一件。',
    '不要把它变成过度工作的压力。',
    30,
    '{"duration_minutes": 20}'::jsonb
  ),
  (
    'warm_check_in_message',
    'zh',
    'relationship',
    array['relationship-tension', 'lonely', 'low-connection'],
    'low',
    '发一条温和问候',
    '低压力的问候能重新打开连接，而不必马上进入沉重对话。',
    '给一个你信任的人发一条简单善意的问候，不附带请求。',
    '尊重边界；不适用于让你感到不安全的关系。',
    40,
    '{"channel": "message"}'::jsonb
  ),
  (
    'evening_reflection_three_lines',
    'zh',
    'routine',
    array['restless', 'unclear-patterns', 'emotional-noise'],
    'low',
    '用三行结束今天',
    '简短复盘能帮助你在睡前区分真正的信号和情绪噪音。',
    '今晚写三行：什么支持了你，什么消耗了你，你准备放下什么。',
    '如果书写让你更不舒服，就暂停并改做稳定身心的活动。',
    50,
    '{"duration_minutes": 5, "time_of_day": "evening"}'::jsonb
  ),
  (
    'gentle_walk_light',
    'zh',
    'wellbeing',
    array['stagnant', 'low-mood', 'low-energy'],
    'low',
    '给自己一个轻量透气时段',
    '轻微移动和自然光能帮助注意力换挡，也让节奏重新变得可感。',
    '到户外或窗边待五到十分钟，节奏保持轻松。',
    '请按自己的身体和环境选择合适方式；这不构成医疗建议。',
    60,
    '{"duration_minutes": 10}'::jsonb
  )
on conflict (rule_key, language) do update set
  category = excluded.category,
  trigger_tags = excluded.trigger_tags,
  severity = excluded.severity,
  title = excluded.title,
  rationale = excluded.rationale,
  action_template = excluded.action_template,
  safety_note = excluded.safety_note,
  is_active = true,
  priority = excluded.priority,
  metadata = excluded.metadata,
  updated_at = now();

commit;
